In [33]:
import cv2
import numpy as np
import skimage as sk

img_100 = io.imread('ultramarine_100.jpg')

In [20]:
img[1,1][1]

94

In [66]:
img_con_100 = sk.color.convert_colorspace(img_100, 'RGB', 'HSV')

In [67]:
img_con_100

array([[[0.65804598, 0.40277778, 0.56470588],
        [0.66233766, 0.44767442, 0.6745098 ],
        [0.66233766, 0.45833333, 0.65882353],
        ...,
        [0.66666667, 0.375     , 0.62745098],
        [0.66954023, 0.31351351, 0.7254902 ],
        [0.68333333, 0.31914894, 0.7372549 ]],

       [[0.65804598, 0.4       , 0.56862745],
        [0.66233766, 0.4556213 , 0.6627451 ],
        [0.66233766, 0.44767442, 0.6745098 ],
        ...,
        [0.66666667, 0.37267081, 0.63137255],
        [0.66954023, 0.35582822, 0.63921569],
        [0.68333333, 0.34482759, 0.68235294]],

       [[0.65804598, 0.4084507 , 0.55686275],
        [0.66244726, 0.43169399, 0.71764706],
        [0.66233766, 0.4375    , 0.69019608],
        ...,
        [0.66666667, 0.35928144, 0.65490196],
        [0.66954023, 0.38410596, 0.59215686],
        [0.68333333, 0.36144578, 0.65098039]],

       ...,

       [[0.67730496, 0.30128205, 0.61176471],
        [0.68382353, 0.38202247, 0.69803922],
        [0.6840796 , 0

In [68]:
average = img_con_100.mean(axis=0).mean(axis=0)

In [75]:
average = img_con_100.mean(axis=0)

In [79]:
average.shape

(155, 3)

In [70]:
img_75 = io.imread('ultramarine_75.jpg')

In [71]:
img_con_75 = sk.color.convert_colorspace(img_75, 'RGB', 'HSV')

In [77]:
average_75 = img_con_75.mean(axis=0)
average_75

array([[0.65727637, 0.47373685, 0.55647059],
       [0.65241154, 0.52338331, 0.63607843],
       [0.65337366, 0.51262165, 0.64784314],
       [0.6624149 , 0.45450274, 0.62980392],
       [0.66101979, 0.41970064, 0.63529412],
       [0.66271867, 0.38132675, 0.63862745],
       [0.66474754, 0.35051582, 0.68745098],
       [0.66980547, 0.34339786, 0.68568627],
       [0.67965034, 0.33730362, 0.70764706],
       [0.68266977, 0.33914066, 0.69254902],
       [0.68353782, 0.33104997, 0.69784314],
       [0.68800493, 0.32278425, 0.69627451],
       [0.6861689 , 0.31505852, 0.71254902],
       [0.67974973, 0.31071362, 0.69235294],
       [0.67958274, 0.30273162, 0.70196078],
       [0.67826001, 0.28692802, 0.71509804],
       [0.67742986, 0.28115165, 0.72156863],
       [0.6804134 , 0.29260801, 0.69490196],
       [0.68990843, 0.29355917, 0.68745098],
       [0.69044834, 0.28207377, 0.71137255],
       [0.69024118, 0.28680173, 0.69431373],
       [0.67813078, 0.27267049, 0.69764706],
       [0.

In [78]:
img_50 = io.imread('ultramarine_50.jpg')
img_con_50 = sk.color.convert_colorspace(img_50, 'RGB', 'hsv')
average_50 = img_con_50.mean(axis=0)
average_50

array([[0.69362748, 0.26615529, 0.74411765],
       [0.69439681, 0.2388735 , 0.75431373],
       [0.69497128, 0.23763085, 0.76235294],
       [0.70110506, 0.25172494, 0.7545098 ],
       [0.70351796, 0.24736263, 0.74941176],
       [0.70239161, 0.24347614, 0.76019608],
       [0.70213662, 0.23861936, 0.77705882],
       [0.7031827 , 0.237427  , 0.76078431],
       [0.70215201, 0.23999949, 0.75627451],
       [0.70304168, 0.23659849, 0.74882353],
       [0.70304168, 0.23358554, 0.75862745],
       [0.70362118, 0.22845235, 0.75823529],
       [0.70394076, 0.23056619, 0.75      ],
       [0.70300805, 0.22800165, 0.75019608],
       [0.70320222, 0.22431786, 0.75647059],
       [0.70357877, 0.21503453, 0.77529412],
       [0.70369656, 0.22074924, 0.76058824],
       [0.70345439, 0.21483408, 0.77117647],
       [0.70177779, 0.21217968, 0.78294118],
       [0.7007012 , 0.22395747, 0.76039216],
       [0.70056231, 0.22735826, 0.75117647],
       [0.70010893, 0.22257911, 0.7645098 ],
       [0.